import React from "react";

export const S = {
  page: {
    minHeight: "100vh",
    background: "var(--page-gradient)",
    color: "#18231b",
    fontFamily: "'Manrope', sans-serif",
    fontWeight: 400,
    lineHeight: 1.6,
    overflowX: "hidden",
    position: "relative",
  } as React.CSSProperties,
  container: { maxWidth: 1280, margin: "0 auto", padding: "0 clamp(20px, 4vw, 40px)" } as React.CSSProperties,
  section: { position: "relative", overflow: "hidden" } as React.CSSProperties,
  nav: (scrolled: boolean): React.CSSProperties => ({
    position: "fixed", top: 0, left: 0, right: 0, zIndex: 100,
    padding: "0 clamp(20px, 4vw, 40px)", height: 78,
    display: "flex", alignItems: "center", justifyContent: "space-between",
    background: scrolled ? "rgba(255,255,255,0.92)" : "rgba(255,255,255,0.72)",
    backdropFilter: "blur(22px)", WebkitBackdropFilter: "blur(22px)",
    borderBottom: "1px solid rgba(24,35,27,0.08)",
    boxShadow: scrolled ? "0 12px 40px rgba(31,52,36,0.09)" : "none",
    transition: "background 0.3s, box-shadow 0.3s",
  }),
  navLogo: {
    display: "flex", alignItems: "center", gap: 10,
    fontFamily: "'Plus Jakarta Sans', sans-serif", fontWeight: 800, fontSize: 22,
    letterSpacing: "-0.03em", textDecoration: "none", color: "#18231b",
  } as React.CSSProperties,
  logoMark: {
    width: 36, height: 36, borderRadius: 12,
    background: "linear-gradient(135deg, #22a653, #15803d)",
    display: "flex", alignItems: "center", justifyContent: "center",
    boxShadow: "0 8px 24px rgba(21,128,61,0.22)",
  } as React.CSSProperties,
  navLinks: { display: "flex", gap: 32, listStyle: "none" } as React.CSSProperties,
  navLink: {
    color: "#4d5d51", textDecoration: "none",
    fontSize: 15, fontWeight: 600, transition: "color 0.2s", cursor: "pointer",
  } as React.CSSProperties,
  btnPrimary: {
    display: "inline-flex", alignItems: "center", gap: 8,
    padding: "13px 28px", borderRadius: 999,
    fontFamily: "'Plus Jakarta Sans', sans-serif", fontSize: 13, fontWeight: 700,
    cursor: "pointer", border: "none", letterSpacing: "0.02em",
    background: "#15803d", color: "#ffffff",
    boxShadow: "0 10px 30px rgba(21,128,61,0.22)",
    transition: "all 0.25s cubic-bezier(0.34,1.56,0.64,1)", whiteSpace: "nowrap",
  } as React.CSSProperties,
  btnPrimaryLg: {
    display: "inline-flex", alignItems: "center", gap: 8,
    padding: "17px 38px", borderRadius: 999,
    fontFamily: "'Plus Jakarta Sans', sans-serif", fontSize: 15, fontWeight: 700,
    cursor: "pointer", border: "none", letterSpacing: "0.02em",
    background: "#15803d", color: "#ffffff",
    boxShadow: "0 16px 40px rgba(21,128,61,0.20)",
    transition: "all 0.25s cubic-bezier(0.34,1.56,0.64,1)",
  } as React.CSSProperties,
  btnGhost: {
    display: "inline-flex", alignItems: "center", gap: 8,
    padding: "12px 24px", borderRadius: 999,
    fontFamily: "'Plus Jakarta Sans', sans-serif", fontSize: 13, fontWeight: 600,
    cursor: "pointer", background: "transparent",
    color: "#27342b", border: "1px solid rgba(24,35,27,0.12)",
    backdropFilter: "blur(18px)", WebkitBackdropFilter: "blur(18px)",
    backgroundColor: "rgba(255,255,255,0.74)",
    transition: "all 0.25s cubic-bezier(0.34,1.56,0.64,1)", letterSpacing: "0.02em",
  } as React.CSSProperties,
  btnGhostLg: {
    display: "inline-flex", alignItems: "center", gap: 8,
    padding: "16px 36px", borderRadius: 999,
    fontFamily: "'Plus Jakarta Sans', sans-serif", fontSize: 15, fontWeight: 600,
    cursor: "pointer", background: "transparent",
    color: "#27342b", border: "1px solid rgba(24,35,27,0.12)",
    backdropFilter: "blur(18px)", WebkitBackdropFilter: "blur(18px)",
    backgroundColor: "rgba(255,255,255,0.74)",
    transition: "all 0.25s cubic-bezier(0.34,1.56,0.64,1)", letterSpacing: "0.02em",
  } as React.CSSProperties,
  gradientText: {
    color: "#166534",
  } as React.CSSProperties,
  sectionTagCenter: {
    fontFamily: "'IBM Plex Mono', monospace", fontSize: 11, fontWeight: 500,
    color: "#166534", letterSpacing: "0.12em", textTransform: "uppercase",
    display: "inline-block",
    background: "#edf7ef", border: "1px solid #cce8d2",
    borderRadius: 100, padding: "5px 14px", marginBottom: 16,
    backdropFilter: "blur(14px)", WebkitBackdropFilter: "blur(14px)",
  } as React.CSSProperties,
  sectionTitle: {
    fontFamily: "'Plus Jakarta Sans', sans-serif",
    fontSize: "clamp(30px,4vw,50px)",
    fontWeight: 800, marginBottom: 16,
    letterSpacing: "-0.02em", lineHeight: 1.1,
  } as React.CSSProperties,
  sectionSub: {
    fontSize: 16, color: "#667069", maxWidth: 600, lineHeight: 1.75,
  } as React.CSSProperties,
  glass: {
    background: "rgba(255,255,255,0.86)",
    border: "1px solid rgba(24,35,27,0.09)",
    borderRadius: 24,
    backdropFilter: "blur(26px)",
    WebkitBackdropFilter: "blur(26px)",
    boxShadow: "0 20px 60px rgba(31,52,36,0.10)",
  } as React.CSSProperties,
  featureCard: {
    padding: 28, borderRadius: 20,
    background: "rgba(255,255,255,0.82)",
    border: "1px solid rgba(24,35,27,0.09)",
    position: "relative", overflow: "hidden",
    backdropFilter: "blur(22px)", WebkitBackdropFilter: "blur(22px)",
    transition: "border-color 0.3s, transform 0.3s, box-shadow 0.3s, background 0.3s",
    cursor: "default",
  } as React.CSSProperties,
  howStep: {
    padding: "28px 24px",
    background: "rgba(255,255,255,0.82)",
    borderWidth: 1,
    borderStyle: "solid",
    borderRadius: 20, position: "relative",
    backdropFilter: "blur(22px)", WebkitBackdropFilter: "blur(22px)",
    transition: "border-color 0.3s, background 0.3s, transform 0.3s",
    cursor: "default",
  } as React.CSSProperties,
  ctaSection: {
    padding: "120px clamp(20px, 4vw, 40px)", textAlign: "center",
    background: "radial-gradient(ellipse 60% 60% at 50% 100%, rgba(34,197,94,0.10) 0%, transparent 70%)",
    position: "relative", overflow: "hidden",
  } as React.CSSProperties,
  footer: {
    borderTop: "1px solid rgba(24,35,27,0.08)",
    padding: "60px 0 40px", background: "rgba(255,255,255,0.72)", backdropFilter: "blur(24px)", WebkitBackdropFilter: "blur(24px)",
  } as React.CSSProperties,
  footerTitle: {
    fontFamily: "'Plus Jakarta Sans',sans-serif", fontSize: 13, fontWeight: 700,
    marginBottom: 16, color: "#27342b", letterSpacing: "0.05em",
  } as React.CSSProperties,
  footerLink: {
    display: "block", color: "#667069", textDecoration: "none",
    fontSize: 14, marginBottom: 10, transition: "color 0.2s",
  } as React.CSSProperties,
  footerSocialIcon: {
    width: 36, height: 36, borderRadius: 10,
    background: "#ffffff", border: "1px solid rgba(24,35,27,0.10)",
    display: "flex", alignItems: "center", justifyContent: "center",
    fontSize: 12, cursor: "pointer", textDecoration: "none", color: "#4d5d51",
    transition: "all 0.2s",
  } as React.CSSProperties,
};
